# Generated by Django 4.2.1 on 2023-05-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_original', models.CharField(max_length=100)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
