# Generated by Django 4.2.1 on 2023-05-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='descricao',
        ),
    ]
